title: Leon Kiefer's project site
description: Collection of my current, past and future projects.

url: "https://legion2.github.io"
remote_theme: lorepirri/cayman-blog
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name: Leon Kiefer
  twitter: Legion2Leon
twitter:
  username: Legion2Leon

header_page_refs: ['now', 'about']

google_site_verification: gzea0bCYZXrELvHrSQSA-cPcpEhi_PPWvj-Pp1rJtpA
